### ISSUE TITLE
More detailed information about changing the collection

### ISSUE THREAD

**Issue by Qsppl** [henryruhs/rxjs-collection#3]
Currently we can only track changes to the entire collection:

```TS
const reactiveMap = new ReactiveMap();

reactiveMap.subscribe({
        next: collection => console.log('Observer got a next collection state: ', collection),
        error: err => console.error('Observer got an error: ', err),
        complete: () => console.log('Observer got a complete notification'),
    });
```

But often it is necessary to perform work related only to the added elements, but not to the entire collection at once:

```TS
const reactiveMap = new ReactiveMap();

reactiveMap.subscribe({
        next: (collection, increment, modified, decrement) => {
            console.log('Observer got a next collection state: ', collection);
            console.log('The following values ​​have been added: ', increment);
            console.log('The following values ​​have been modified: ', modified);
            console.log('The following values ​​have been removed: ', decrement);
        },
        error: err => console.error('Observer got an error: ', err),
        complete: () => console.log('Observer got a complete notification'),
    });
```

**Comment by henryruhs** [comment]
@Qsppl Hey, this library is not active developed. If you are looking for such a feature, please send a pull request and some testing to cover such new feature.

**Comment by Qsppl** [comment]
Okay, I'll do it later

**Comment by Qsppl** [comment]
My project only needs reactive collections to update component states incrementally. All the other functionality of RxJS was not needed, so I replaced RxJS+rxjs-collection with a simple two-line function that works with [EventTarget API](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/EventTarget).
```TS
export class ReactiveMap<Key, Value> extends Map<Key, Value> {
    public subscribe(listener: Handler<CollectionChanges<[Key, Value]>>): Subscription {
        this.emitter.on("next", listener)
        return { unsubscribe: () => this.emitter.off("next", listener) }
    }
}
```
I am closing the task because I no longer need the functionality specified in it and I most likely will not implement it.
